const festivalEssentialsMap = {
  "ganesha chaturthi": [
    "Ganesha idol",
    "Turmeric",
    "Kumkum",
    "Sandalwood paste",
    "Akshata (rice)",
    "Durva grass",
    "Red flowers",
    "Garland",
    "Modak",
    "Coconut",
    "Bananas",
    "Betel leaves",
    "Betel nuts",
    "Incense sticks",
    "Camphor",
    "Cotton wicks",
    "Ghee/oil",
    "Kalash",
    "Mango leaves",
    "Panchamrit ingredients",
    "Pooja thali"
  ],

  "ganesha visarjan": [
    "Ganesha idol",
    "Flowers",
    "Garland",
    "Durva grass",
    "Turmeric",
    "Kumkum",
    "Sandalwood",
    "Akshata",
    "Coconut",
    "Fruits",
    "Modak/prasad",
    "Incense sticks",
    "Camphor",
    "Cotton wicks",
    "Ghee/oil",
    "Kalash",
    "Pooja thali",
    "Red/yellow cloth"
  ],

  "maha shivaratri": [
    "Shiva Lingam",
    "Bilva leaves",
    "Milk",
    "Curd",
    "Honey",
    "Ghee",
    "Sugar",
    "Ganga water",
    "Sandalwood",
    "Vibhuti",
    "Rudraksha",
    "White flowers",
    "Dhatura",
    "Bael fruit",
    "Coconut",
    "Fruits",
    "Incense sticks",
    "Camphor",
    "Cotton wicks"
  ],

  "rama navami": [
    "Rama idol/image",
    "Sita idol/image",
    "Lakshmana idol/image",
    "Hanuman idol/image",
    "Tulsi leaves",
    "Flowers",
    "Garland",
    "Turmeric",
    "Kumkum",
    "Sandalwood",
    "Akshata",
    "Coconut",
    "Fruits",
    "Panakam ingredients",
    "Kosambari ingredients",
    "Incense sticks",
    "Camphor",
    "Cotton wicks"
  ],

  "krishna janmashtami": [
    "Krishna idol",
    "Baby Krishna cradle",
    "Yellow cloth",
    "Tulsi leaves",
    "Flowers",
    "Garland",
    "Butter",
    "Milk",
    "Curd",
    "Honey",
    "Panchamrit ingredients",
    "Fruits",
    "Makhan mishri",
    "Coconut",
    "Sandalwood",
    "Kumkum",
    "Incense sticks",
    "Camphor",
    "Cotton wicks"
  ],

  "hanuman jayanti": [
    "Hanuman idol/image",
    "Sindoor",
    "Jasmine oil",
    "Betel leaves",
    "Betel nuts",
    "Red flowers",
    "Garland",
    "Tulsi leaves",
    "Coconut",
    "Bananas",
    "Jaggery",
    "Boondi/ladoo",
    "Turmeric",
    "Kumkum",
    "Sandalwood",
    "Incense sticks",
    "Camphor"
  ],

  "narasimha jayanti": [
    "Narasimha idol/image",
    "Lakshmi idol/image",
    "Tulsi leaves",
    "Flowers",
    "Garland",
    "Turmeric",
    "Kumkum",
    "Sandalwood",
    "Akshata",
    "Coconut",
    "Fruits",
    "Panchamrit",
    "Betel leaves",
    "Betel nuts",
    "Incense sticks",
    "Camphor",
    "Cotton wicks"
  ],

  "vamana jayanti": [
    "Vamana idol/image",
    "Vishnu idol/image",
    "Tulsi leaves",
    "Flowers",
    "Garland",
    "Turmeric",
    "Kumkum",
    "Sandalwood",
    "Akshata",
    "Coconut",
    "Fruits",
    "Panchamrit",
    "Betel leaves",
    "Betel nuts",
    "Incense sticks",
    "Camphor",
    "Ghee/oil"
  ],

  "parashurama jayanti": [
    "Parashurama idol/image",
    "Vishnu idol/image",
    "Tulsi leaves",
    "Flowers",
    "Garland",
    "Turmeric",
    "Kumkum",
    "Sandalwood",
    "Akshata",
    "Coconut",
    "Fruits",
    "Panchamrit",
    "Betel leaves",
    "Betel nuts",
    "Incense sticks",
    "Camphor",
    "Cotton wicks"
  ],

  "buddha purnima": [
    "Buddha idol/image",
    "White/yellow flowers",
    "Lotus flowers",
    "Garland",
    "Sandalwood",
    "Akshata",
    "Incense sticks",
    "Camphor",
    "Oil lamp",
    "Fruits",
    "Milk",
    "Honey",
    "Water",
    "Coconut",
    "Pooja plate"
  ],

  "durga puja": [
    "Durga idol/image",
    "Red sari/cloth",
    "Red flowers",
    "Lotus flowers",
    "Garland",
    "Durva grass",
    "Bilva leaves",
    "Turmeric",
    "Kumkum",
    "Sandalwood",
    "Akshata",
    "Coconut",
    "Fruits",
    "Betel leaves",
    "Betel nuts",
    "Sweets",
    "Incense sticks",
    "Camphor",
    "Diyas",
    "Ghee/oil"
  ],

  "navratri": [
    "Durga/Devi idol",
    "Kalash",
    "Mango leaves",
    "Coconut",
    "Red cloth",
    "Kumkum",
    "Turmeric",
    "Akshata",
    "Flowers",
    "Garland",
    "Durva",
    "Fruits",
    "Dry fruits",
    "Sweets",
    "Betel leaves",
    "Betel nuts",
    "Incense sticks",
    "Camphor",
    "Diyas",
    "Ghee/oil",
    "Navratri kalash items"
  ],

  "vijayadashami / dussehra": [
    "Durga idol/image",
    "Rama idol/image",
    "Hanuman idol/image",
    "Flowers",
    "Garland",
    "Kumkum",
    "Turmeric",
    "Sandalwood",
    "Akshata",
    "Coconut",
    "Fruits",
    "Sweets",
    "Betel leaves",
    "Betel nuts",
    "Incense sticks",
    "Camphor",
    "Diyas"
  ],

  "diwali puja": [
    "Lakshmi idol",
    "Ganesha idol",
    "Saraswati idol",
    "Red/yellow cloth",
    "Lotus flowers",
    "Marigold flowers",
    "Garland",
    "Kumkum",
    "Turmeric",
    "Sandalwood",
    "Akshata",
    "Coins",
    "New account book/ledger",
    "Coconut",
    "Fruits",
    "Sweets",
    "Dry fruits",
    "Betel leaves",
    "Betel nuts",
    "Diyas",
    "Cotton wicks",
    "Ghee/oil",
    "Incense sticks",
    "Camphor"
  ],

  "lakshmi puja": [
    "Lakshmi idol/image",
    "Ganesha idol",
    "Kalash",
    "Coconut",
    "Mango leaves",
    "Lotus flowers",
    "Red flowers",
    "Garland",
    "Kumkum",
    "Turmeric",
    "Sandalwood",
    "Akshata",
    "Coins",
    "Rice",
    "Fruits",
    "Sweets",
    "Betel leaves",
    "Betel nuts",
    "Incense sticks",
    "Camphor",
    "Diyas",
    "Cotton wicks",
    "Ghee/oil"
  ],

  "dhanteras": [
    "Lakshmi idol",
    "Ganesha idol",
    "Dhanvantari image",
    "New utensils",
    "Silver/gold items",
    "Coins",
    "Rice",
    "Kumkum",
    "Turmeric",
    "Flowers",
    "Garland",
    "Coconut",
    "Fruits",
    "Sweets",
    "Betel leaves",
    "Betel nuts",
    "Diyas",
    "Cotton wicks",
    "Ghee/oil",
    "Incense sticks",
    "Camphor"
  ],

  "govardhan puja": [
    "Krishna idol",
    "Govardhan mountain representation",
    "Cow/bull decoration items",
    "Flowers",
    "Garland",
    "Tulsi leaves",
    "Kumkum",
    "Turmeric",
    "Sandalwood",
    "Akshata",
    "Cow dung (traditional)",
    "Annakut food offerings",
    "Fruits",
    "Sweets",
    "Coconut",
    "Incense sticks",
    "Camphor",
    "Diyas"
  ],

  "bhai dooj": [
    "Bhai Dooj thali",
    "Kumkum",
    "Sandalwood",
    "Akshata",
    "Roli",
    "Coconut",
    "Sweets",
    "Fruits",
    "Betel leaves",
    "Betel nuts",
    "Diya",
    "Cotton wicks",
    "Incense sticks",
    "Gifts"
  ],

  "saraswati puja / vasant panchami": [
    "Saraswati idol/image",
    "Books",
    "Pens",
    "Musical instruments",
    "Yellow cloth",
    "Yellow flowers",
    "Marigold flowers",
    "Garland",
    "Turmeric",
    "Kumkum",
    "Sandalwood",
    "Akshata",
    "Fruits",
    "Sweets",
    "Coconut",
    "Betel leaves",
    "Betel nuts",
    "Incense sticks",
    "Camphor",
    "Diyas"
  ],

  "jagannath rath yatra": [
    "Jagannath idol",
    "Balabhadra idol",
    "Subhadra idol",
    "Chandan/sandalwood",
    "Tulsi leaves",
    "Flowers",
    "Garland",
    "Yellow/red cloth",
    "Kumkum",
    "Turmeric",
    "Akshata",
    "Coconut",
    "Fruits",
    "Mahaprasad offerings",
    "Sweets",
    "Incense sticks",
    "Camphor",
    "Diyas"
  ],

  "guru purnima": [
    "Guru photo/idol",
    "Guru paduka",
    "Flowers",
    "Garland",
    "Sandalwood",
    "Kumkum",
    "Turmeric",
    "Akshata",
    "Coconut",
    "Fruits",
    "Sweets",
    "Betel leaves",
    "Betel nuts",
    "Incense sticks",
    "Camphor",
    "Diya"
  ],

  "raksha bandhan": [
    "Rakhi",
    "Kumkum/Roli",
    "Akshata",
    "Sandalwood",
    "Diya",
    "Cotton wicks",
    "Incense sticks",
    "Sweets",
    "Coconut",
    "Fruits",
    "Gift",
    "Pooja thali",
    "Kalash"
  ],

  "akshaya tritiya": [
    "Lakshmi idol",
    "Vishnu idol",
    "Ganesha idol",
    "Tulsi leaves",
    "Yellow flowers",
    "Lotus",
    "Turmeric",
    "Kumkum",
    "Sandalwood",
    "Akshata",
    "Gold/silver items",
    "Coins",
    "Coconut",
    "Fruits",
    "Sweets",
    "Betel leaves",
    "Betel nuts",
    "Incense sticks",
    "Camphor",
    "Diyas"
  ],

  "ganga dussehra": [
    "Ganga Maa image",
    "Kalash",
    "Ganga water",
    "Flowers",
    "Garland",
    "Tulsi leaves",
    "Sandalwood",
    "Kumkum",
    "Turmeric",
    "Akshata",
    "Coconut",
    "Fruits",
    "Sweets",
    "Betel leaves",
    "Betel nuts",
    "Incense sticks",
    "Camphor",
    "Diyas"
  ],

  "chhath puja": [
    "Bamboo soop",
    "Bamboo basket",
    "Sugarcane",
    "Banana",
    "Coconut",
    "Apple",
    "Orange",
    "Other seasonal fruits",
    "Thekua",
    "Rice",
    "Jaggery",
    "Wheat flour",
    "Milk",
    "Ghee",
    "Diyas",
    "Cotton wicks",
    "Incense sticks",
    "Flowers",
    "Kalash",
    "New cloth"
  ],

  "vishwakarma puja": [
    "Vishwakarma idol/image",
    "Tools",
    "Machinery decoration items",
    "Yellow/red cloth",
    "Flowers",
    "Garland",
    "Turmeric",
    "Kumkum",
    "Sandalwood",
    "Akshata",
    "Coconut",
    "Fruits",
    "Sweets",
    "Betel leaves",
    "Betel nuts",
    "Incense sticks",
    "Camphor",
    "Diyas",
    "Ghee/oil"
  ],

  "karwa chauth": [
    "Karwa/karva",
    "Karwa Chauth thali",
    "Shiva-Parvati idol/image",
    "Ganesha idol",
    "Chandra image",
    "Kumkum",
    "Roli",
    "Mehendi",
    "Sindoor",
    "Bangles",
    "Bindi",
    "Flowers",
    "Garland",
    "Akshata",
    "Coconut",
    "Fruits",
    "Sweets",
    "Matki",
    "Diya",
    "Sieve/channi",
    "Incense sticks"
  ],

  "vat savitri vrat": [
    "Vat/Savitri image",
    "Banyan tree worship items",
    "Red/yellow thread",
    "Kumkum",
    "Turmeric",
    "Sandalwood",
    "Akshata",
    "Flowers",
    "Garland",
    "Fruits",
    "Coconut",
    "Sweets",
    "Betel leaves",
    "Betel nuts",
    "Sindoor",
    "Bangles",
    "Incense sticks",
    "Camphor",
    "Diya"
  ],

  "shani jayanti": [
    "Shani Dev idol/image",
    "Black cloth",
    "Black sesame seeds",
    "Mustard oil",
    "Black urad dal",
    "Iron items",
    "Blue/black flowers",
    "Akshata",
    "Coconut",
    "Fruits",
    "Jaggery",
    "Betel leaves",
    "Betel nuts",
    "Incense sticks",
    "Camphor",
    "Diya",
    "Cotton wicks"
  ],

  "gudi padwa": [
    "Gudi flag",
    "Bamboo stick",
    "Silk/new cloth",
    "Neem leaves",
    "Mango leaves",
    "Sugar crystals",
    "Garland",
    "Turmeric",
    "Kumkum",
    "Sandalwood",
    "Akshata",
    "Coconut",
    "Fruits",
    "Sweets",
    "Kalash",
    "Incense sticks",
    "Camphor",
    "Diya"
  ],

  "ugadi": [
    "Neem leaves",
    "Raw mango",
    "Jaggery",
    "Tamarind",
    "Pepper",
    "Salt",
    "Coconut",
    "Turmeric",
    "Kumkum",
    "Flowers",
    "Mango leaves",
    "Kalash",
    "Fruits",
    "Sweets",
    "Betel leaves",
    "Betel nuts",
    "Incense sticks",
    "Camphor",
    "Diya"
  ],

  "makar sankranti": [
    "Sesame seeds",
    "Jaggery",
    "Sugarcane",
    "Rice",
    "Turmeric",
    "Kumkum",
    "Flowers",
    "Coconut",
    "Fruits",
    "Til ladoo",
    "Sweets",
    "Mango leaves",
    "Kalash",
    "Betel leaves",
    "Betel nuts",
    "Incense sticks",
    "Camphor",
    "Diyas"
  ],

  "pongal": [
    "New clay Pongal pot",
    "Turmeric plant",
    "Sugarcane",
    "Raw rice",
    "Milk",
    "Jaggery",
    "Moong dal",
    "Cashews",
    "Raisins",
    "Cardamom",
    "Ghee",
    "Banana",
    "Coconut",
    "Mango leaves",
    "Turmeric",
    "Kumkum",
    "Flowers",
    "Betel leaves",
    "Betel nuts",
    "Diya"
  ],

  "puthandu": [
    "Mango leaves",
    "Neem flowers",
    "Raw mango",
    "Banana",
    "Coconut",
    "Flowers",
    "Garland",
    "Turmeric",
    "Kumkum",
    "Sandalwood",
    "Akshata",
    "Betel leaves",
    "Betel nuts",
    "Fruits",
    "Sweets",
    "New clothes",
    "Kalash",
    "Incense sticks",
    "Camphor",
    "Diya"
  ],

  "karthigai deepam": [
    "Clay diyas",
    "Cotton wicks",
    "Sesame oil/ghee",
    "Thiruvilakku",
    "Karthigai lamps",
    "Flowers",
    "Garland",
    "Kumkum",
    "Turmeric",
    "Sandalwood",
    "Akshata",
    "Coconut",
    "Fruits",
    "Pori",
    "Appam",
    "Betel leaves",
    "Betel nuts",
    "Incense sticks",
    "Camphor"
  ],

  "panguni uthiram": [
    "Murugan idol/image",
    "Valli idol/image",
    "Deivanai idol/image",
    "Shiva-Parvati image",
    "Flowers",
    "Garland",
    "Kavadi decoration items",
    "Milk",
    "Panchamrit",
    "Coconut",
    "Fruits",
    "Turmeric",
    "Kumkum",
    "Sandalwood",
    "Akshata",
    "Betel leaves",
    "Betel nuts",
    "Incense sticks",
    "Camphor",
    "Diyas"
  ],

  "onam": [
    "Mahabali image/idol",
    "Vishnu/Vamana image",
    "Fresh flowers",
    "Pookalam flowers",
    "Banana leaves",
    "Rice",
    "Coconut",
    "Fruits",
    "Banana",
    "Jaggery",
    "Payasam ingredients",
    "Turmeric",
    "Kumkum",
    "Sandalwood",
    "Betel leaves",
    "Betel nuts",
    "Incense sticks",
    "Camphor",
    "Diyas"
  ],

  "vishu": [
    "Krishna idol/image",
    "Vishukkani items",
    "Brass lamp",
    "Rice",
    "Fruits",
    "Vegetables",
    "Cucumber",
    "Coconut",
    "Betel leaves",
    "Betel nuts",
    "Gold/coins",
    "Mirror",
    "Yellow flowers",
    "Turmeric",
    "Kumkum",
    "Sandalwood",
    "Incense sticks",
    "Camphor",
    "Diyas",
    "New clothes"
  ],

  "ashtami rohini": [
    "Krishna/Balakrishna idol",
    "Tulsi leaves",
    "Butter",
    "Milk",
    "Curd",
    "Honey",
    "Panchamrit",
    "Yellow cloth",
    "Flowers",
    "Garland",
    "Sandalwood",
    "Kumkum",
    "Turmeric",
    "Akshata",
    "Coconut",
    "Fruits",
    "Sweets",
    "Incense sticks",
    "Camphor",
    "Diyas"
  ]
};

export default festivalEssentialsMap;